# This workflow will build a Java project with Maven and run the provide Unit Tests

name: Maven Build and Testing

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Maven Build and Tests
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run tests with Maven
      run: mvn test
    

